In [1]:
import plotly.express as px
import pandas as pd
import numpy as np
import folium
import json
import geopandas as gpd
import folium.plugins

In [2]:
data2 = pd.read_csv("평일일별추정교통량.csv")
data2

   읍면동명       통행차량
0   골약동  1583348.5
1   광양읍  5874784.6
2   광영동   490856.8
3   금호동   624073.3
4   다압면    95999.7
5   봉강면   242427.9
6   옥곡면   819384.8
7   옥룡면   270387.7
8   중마동  2871874.4
9   진상면   259372.3
10  진월면   440388.4
11  태인동   357040.1

In [3]:
gwangyang = gpd.read_file("20.광양시_행정경계(읍면동).geojson")
gwangyang

   ADM_DR_CD ADM_DR_NM                                           geometry
0    3606031       봉강면  MULTIPOLYGON (((127.58037 35.10902, 127.58052 ...
1    3606032       옥룡면  MULTIPOLYGON (((127.59872 35.12006, 127.59919 ...
2    3606033       옥곡면  MULTIPOLYGON (((127.64878 35.03547, 127.64902 ...
3    3606034       진상면  MULTIPOLYGON (((127.65639 35.11680, 127.65698 ...
4    3606035       진월면  MULTIPOLYGON (((127.75715 35.05502, 127.75716 ...
5    3606036       다압면  MULTIPOLYGON (((127.64117 35.16850, 127.64140 ...
6    3606051       골약동  MULTIPOLYGON (((127.68056 34.92848, 127.68105 ...
7    3606053       중마동  MULTIPOLYGON (((127.70376 34.96198, 127.70542 ...
8    3606054       광영동  MULTIPOLYGON (((127.71676 34.96939, 127.71691 ...
9    3606055       태인동  MULTIPOLYGON (((127.76162 34.95988, 127.76163 ...
10   3606056       금호동  MULTIPOLYGON (((127.73203 34.95128, 127.73243 ...
11   3606011       광양읍  MULTIPOLYGON (((127.59070 34.91870, 127.59150 ...

In [4]:
GwangYang = folium.Map(location=[34.9406968,127.6958882], zoom_start=11)

In [5]:
choropleth = folium.Choropleth(
    geo_data=gwangyang,
    data=data2,
    columns=['읍면동명', '통행차량'],
    key_on='feature.properties.ADM_DR_NM',
    fill_color='YlOrRd', 
    fill_opacity=0.7, 
    line_opacity=3,
    legend_name='차량통행량',
    highlight=True,
    smooth_factor=0).add_to(GwangYang)

In [6]:
GwangYang.save('./1-2-차량통행량비교.html')